apiVersion: apps/v1
kind: Deployment
metadata:
  name: Loan-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app-container
        image: naveen01s/loanapplication:latest
        ports:
          - containerPort: 3009
        env:
         - name: MONGODB_URI
           value: "mongodb://NEW-P:27017/LoanApplication"
      - name: NEW-P
        image: mongo:latest
        ports:
           - containerPort: 27017